on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - run: |
          sudo apt-get install -y pkg-config libudev-dev libasound2-dev build-essential alsa \
          libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev 
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
    steps:
      - run: |
          sudo apt-get install -y pkg-config libudev-dev libasound2-dev build-essential alsa \
          libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev 
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - run: ls -lha *
      - run: ls -lha target/${{ matrix.target}}/*
      - run: ls -lha target/${{ matrix.target}}/release/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: space-business-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/space_business2_riir*
            assets/
            !target/${{ matrix.target }}/release/space_business2_riir.d


